In [3]:
d = dict(a=2, b='d')

In [12]:
import numpy as np

m = 20
random = 2
np.hstack([np.random.rand(m, random - 1), 0.01*np.random.randn(m, 1)])

array([[  2.92396997e-01,  -7.50918351e-03],
       [  6.20354102e-01,  -9.65305878e-05],
       [  8.32700207e-01,  -8.48379534e-04],
       [  2.67264723e-01,  -1.05806166e-02],
       [  4.05974197e-01,   1.06192283e-02],
       [  8.91230343e-02,   2.59748998e-03],
       [  6.19290177e-01,   5.70721715e-03],
       [  8.97125757e-01,  -7.24966622e-03],
       [  5.34433616e-01,  -2.89021570e-03],
       [  4.89917709e-01,  -9.49177189e-04],
       [  2.01573943e-01,  -1.68069441e-04],
       [  6.91162745e-01,   4.84687145e-03],
       [  7.11265365e-01,   4.75844901e-03],
       [  9.48498733e-01,  -2.17241671e-03],
       [  9.43969862e-01,   1.46357762e-02],
       [  1.82898310e-02,   1.47403923e-02],
       [  4.34380964e-01,  -1.94625974e-03],
       [  2.72596391e-01,  -3.63901532e-03],
       [  1.91557759e-01,  -1.66723926e-02],
       [  1.59267527e-01,   3.53987661e-04]])

In [15]:
vec_1 = np.zeros([50, 1])
vec_1[0:50:2]

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [17]:
np.floor(2.2)

2.0

In [20]:
np.ones([1, 5])

array([[ 1.,  1.,  1.,  1.,  1.]])

In [25]:
a = np.array([[1, 2],
             [3, 4]])
a / np.linalg.norm(a, axis=0)

array([[ 0.31622777,  0.4472136 ],
       [ 0.9486833 ,  0.89442719]])

In [27]:
int(3 / np.sqrt(1 + 9))

0

In [54]:
a = np.array([[1., -1.],
            [1., -1.],
            [2., 2.]])

print a

np.corrcoef(a, rowvar=0)

[[ 1. -1.]
 [ 1. -1.]
 [ 2.  2.]]


array([[ 1.,  1.],
       [ 1.,  1.]])

In [55]:
np.zeros(2)

array([ 0.,  0.])

In [62]:
a[:, 0].T.shape

(3,)

In [73]:
y = np.array([[1], [2], [3]])
np.corrcoef(a, np.tile(y, a.shape[1]), rowvar=0)

array([[ 1.       ,  1.       ,  0.8660254,  0.8660254],
       [ 1.       ,  1.       ,  0.8660254,  0.8660254],
       [ 0.8660254,  0.8660254,  1.       ,  1.       ],
       [ 0.8660254,  0.8660254,  1.       ,  1.       ]])

In [98]:
n = 3
a = -np.diag(np.ones(n)*2) + np.diag(np.ones(n-1), -1) + np.diag(np.ones(n-1), 1)
print a
u,s,v = np.linalg.svd(a)
s

[[-2.  1.  0.]
 [ 1. -2.  1.]
 [ 0.  1. -2.]]


array([ 3.41421356,  2.        ,  0.58578644])

In [5]:
import numpy as np

a = np.array([1, 2, 5, 2, 3])
sorted(a)

[1, 2, 2, 3, 5]